name: "Terraform CI/CD"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # This job runs CI checks on all pushes and PRs.
  ci_checks:
    name: "Terraform CI Checks"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3

      - name: "Terraform Format Check"
        id: fmt
        run: terraform fmt -check -recursive

      - name: "Terraform Init"
        id: init
        run: terraform init

      - name: "Terraform Validate"
        id: validate
        run: terraform validate

  # This job triggers the HCP run, but ONLY on a push to the main branch.
  trigger_hcp_run:
    name: "Trigger HCP Deployment"
    needs: [ci_checks] # This job depends on the CI checks passing
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: "Trigger Terraform Cloud Run"
        uses: hashicorp/tfc-run@v1
        with:
          token: ${{ secrets.HCP_API_TOKEN }}

          # Your HCP organization and workspace names
          organization: "sweepstack-alpha"
          workspace: "sweepstack-iam-management" # Change for your iam-management repo
